### ISSUE TITLE
No more streams available after update

### ISSUE THREAD

**Issue by MATEMATIK-SOSYE** [host505/plugin.video.theoath#45] opened 2022-03-02 05:20 UTC
Greetings @host505! I came to let you know that whatever the update did caused every Pokémon season to NO LONGER contain streams. I like watching Pokémon streams from _The Oath_, but somehow, there are no longer any streams available in ANY of the twenty-four seasons. Will you look into this please?! _Mèsi_! 🙏🏼

**Comment by host505** [comment] 2022-03-02 14:06
Can you be more specific, since which version did it start happening? Also, do you have the latest resolveurl version? Theoath won't work with older ones anymore.
A log would probably help.

**Comment by MATEMATIK-SOSYE** [comment] 2022-03-02 14:10
Well @host505, it is host505.github.io/ , the same one I have always used.

**Comment by host505** [comment] 2022-03-02 17:00
I didn't ask where you got the repository from. I need to know your installed versions of theoath, oathscrapers and resolveurl and also what were the last versions that worked for you. And a theoath.log that captures the problem. Otherwise I won't be able to help.
I checked with the current versions and I got some links - only via rd though.

**Comment by MATEMATIK-SOSYE** [comment] 2022-03-02 18:06
Gwosè! 😒

How exactly do I check the logs for this? I do not know how.

**Comment by MATEMATIK-SOSYE** [comment] 2022-03-02 18:20
After the _Oathscrapers Module_ and _The Oath_ were automatically updated was when I received those errours.

**Comment by jewbmx** [comment] 2022-03-02 20:07
Id guess that it might be a cleantitle issue host505. I did some tests for you two and on my end theoath doesnt find any results for pokemon season 2 or 4 and also the pokemon evolution.  Then on my addon i did the same with some of my scrapers in and i found results. (Scrapers: gowatchseries, 123moviesfree.)
As for the error log all i spotted on both our addons logs were the basic errors you get when scraping doesnt match up in the check title bit of code.

**Comment by host505** [comment] 2022-03-02 22:35
The gowatchseries ajax page that the scraper I have uses does not fetch the first 2 seasons (although they do exist on the site).
I get results for the rest of the seasons though.

**Comment by MATEMATIK-SOSYE** [comment] 2022-03-02 23:22
Mèsi @jewbmx! I am glad you understand what I went through.

**Comment by MATEMATIK-SOSYE** [comment] 2022-03-02 23:24
You received results for which @host505?

**Comment by jewbmx** [comment] 2022-03-03 02:42
Im not really sure what the problem is but id trump it up to a lack of scrapers for toons/animes or the fact that watching those genres with these apps is always a lil poo lol.

**Comment by MATEMATIK-SOSYE** [comment] 2022-03-03 04:45
How did you test these @jewbmx? Were you capable of finding results?

**Comment by host505** [comment] 2022-03-03 06:24
Right. I also haven't seen proof that it got worse since the last updates, nor have I experienced this, so closing.

**Closed by host505** 2022-03-03 06:24 UTC

**Comment by MATEMATIK-SOSYE** [comment] 2022-03-03 06:27
What more do you need @host505? I already gave you everything I knew. Plus, you _still_ have not told me how to search for the log.

**Comment by host505** [comment] 2022-03-03 06:30
This is not a general Kodi education space. You haven't given me anything that I asked you. Only "no sources". I don't have time for this sorry.

**Comment by MATEMATIK-SOSYE** [comment] 2022-03-03 06:40
No @host505! That is MY line. As the owner, you should show RESPECT and sit down with people to go through certain procedures and guide them all the way through no matter HOW long it takes. There was NO need to be rude like you were earlier when I commented "Gwosè". I am the one who does not have time for YOUR disrespect and rudeness. I asked you in the politest way possible, and THIS is how you treat your clients? I bet it is no WONDER you do not have alot of followers. They would not appreciate your tone because they can take a look at THIS and can tell how you REALLY act online when interacting with your peers. You are a childish brat and must think **thrise** before saying anything to people because you will NEVER know how they will retaliate. Take this as a learning lesson. You must think you are big and bad behind your screens, but I BET you will not come in my face and say all of this garbage man to man. That is for sure. Settle down child!

GOODBYE!

**Comment by host505** [comment] 2022-03-03 06:45
Dude thought he was my _client_. WHERE ARE MY SORSEEEEES WAHWAH lol
Go to hell client

**Comment by host505** [comment] 2022-03-03 14:05
Funny indeed. That's why I leave his message here so people can have a laugh.
Also to show what we sometimes get in return for donating our free time so they can have their free stuff.
Client he says, lol I wonder who ripped him off - I refuse to believe people can have such an attitude over free stuff.

**Comment by mrXoo** [comment] 2022-03-04 04:10
Awesome thread. Sooo how much did the guy pay for the oath lol. I’d ask for my money back :)
