### ISSUE TITLE
Streams not starting since last update

### ISSUE THREAD

**Issue by freaktabnl** [host505/plugin.video.theoath#14] opened 2021-01-30 07:02 UTC
Streams not starting since last update. All fine till dialog box shows > click source but streams don't start.

**Comment by host505** [comment] 2021-01-30 09:08
Can't reproduce.
What os are you running kodi on, and what kodi version?
Also, local or trakt indicators?

**Comment by host505** [comment] 2021-01-30 09:48
Yea sorry, found the mistake.
Fix in a few hours.
Thanks.

**Comment by host505** [comment] 2021-01-30 19:24
I pushed new version with a fix for this, please let me know if it works.

**Closed** 2021-02-01 06:12 UTC
