### ISSUE TITLE
The Oath

### ISSUE THREAD

**Issue by ronfrankhill** [host505/plugin.video.theoath#44] opened 2022-03-01 02:59 UTC
The last update yesterday it’s uninstalling the addon and failing dependency. I tried to reinstall the add-on but it wouldn't install. Other users are having the same issue according to what I saw on Reddit etc.

**Comment by host505** [comment] 2022-03-01 06:50
The issue is this: https://github.com/host505/repository.host505/issues/15 and should be fixed now.
Force check for updates.

**Closed** 2022-03-01 10:33 UTC
