### ISSUE TITLE
Not finding a series.

### ISSUE THREAD

**Issue by TNTPro** [host505/plugin.video.theoath#24] opened 2021-05-17 13:54 UTC
Hi there,

If I search for the TV show called "Aaron Needs A Job" the oath fails to find it.  This show is on both the TMDB and Trakt sites.
I also went into my Trakt collection via theoath and although this show is definitely in my collection, it fails to show up in theoath.

Tec

**Comment by host505** [comment] 2021-05-17 18:22
Yea the problem is that trakt doesn't supply imdb id nor tmdb id for that show.
It was in my to-do to change the search api call from trakt to tmdb, which will make the show appear on search.
I also made some more id checks and it now appears under trakt lists as well.
I'll push an update with those fixes soon.

**Comment by host505** [comment] 2021-05-18 12:54
Should be fixed with 037fef462d880dad29d8886fec49b5239c9d0c8f

**Closed by host505** 2021-05-18 12:54 UTC
